config/routes.rb
Activeresume::Application.routes.draw do
  get "welcome/index"
  match 'dashboard' => 'dashboard#index', :as => 'dashboard' 
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  match 'dashboard' => 'dashboard#index', :as => 'user_root'
  
  resources :employments
  resources :educations
  resource :profile
  resources :projects
  resources :publications
  
  root :to => "welcome#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Employment, :user_id => user.id
    can :manage, Education, :user_id => user.id
    can :manage, Project, :user_id => user.id
    can :manage, Profile, :user_id => user.id
    can :manage, Publication, :user_id => user.id
  end
end

app/models/custom_failure.rb
class CustomFailure < Devise::FailureApp
  def redirect_url
    new_user_session_path
  end

  def respond
    if http_auth?
      http_auth
    else
      store_location!
      flash[:alert] = i18n_message unless flash[:notice]
      redirect_to "/"
    end
  end
end

app/models/education.rb
class Education < ActiveRecord::Base
  validates_presence_of :institution_name
end

app/models/employment.rb
class Employment < ActiveRecord::Base
  validates_presence_of :company_name
end

app/models/portfolio_item.rb
class PortfolioItem < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :image, 
      :styles => { :large => "780x585>", :thumbnail => "125x125#" },
      :default_url => '/images/missing_:style.png',
      :storage => :s3,
      :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
      :path => ":image/:id/:style.:extension"
      
  validates_presence_of :title  
  
  validates_attachment_size :image, :less_than => 2.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/x-png', 'image/pjepg']
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :image, 
      :styles => { :large => "780x585>", :thumbnail => "125x125#" },
      :default_url => '/images/missing_:style.png',
      :storage => :s3,
      :s3_credentials => "#{Rails.root}/config/s3.yml",
      :path => ":image/:id/:style.:extension"
      
  validates_presence_of :title  
  
  validates_attachment_size :image, :less_than => 2.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/x-png', 'image/pjepg']
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_one :profile
  has_many :employments
  has_many :educations
  has_many :projects
  has_many :publications

  before_validation :create_profile

  def create_profile
    self.profile ||= Profile.new(:email => self.email)
  end

  def display_name
    profile.first_name.present? ? "#{profile.first_name} #{profile.last_name}".strip : email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @employments = current_user.employments
    @educations = current_user.educations
    @projects = current_user.projects
    @publications = current_user.publications
  end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  load_and_authorize_resource
  skip_authorize_resource :only => [:show]
  
  def new
  end
  
  def create
    @education.user_id = current_user.id
    
    if @education.save
      flash[:notice] = "Education record was successfully created."
      redirect_to dashboard_path
    else
      flash[:alert] = @education.errors.full_messages.join("<br />").html_safe
      render :action => "new"
    end
  end
  
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  load_and_authorize_resource
  skip_authorize_resource :only => [:show]
  
  def new
  end
  
  def create
    @employment.user_id = current_user.id

    if @employment.save
      flash[:notice] = "Employment record was successfully created."
      redirect_to dashboard_path
    else
      flash[:alert] = @employment.errors.full_messages.join("<br /").html_safe
      render :new
    end
  end
  
end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  load_and_authorize_resource
  skip_authorize_resource :only => [:show]
    
  def new
  end
  
  def create
    @portfolio_item.user_id = current_user.id
    if @portfolio_item.save
      redirect_to root_path
    else
      redirect_to new_portfolio_item_path
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  load_and_authorize_resource
  skip_authorize_resource :only => [:show]

  def edit
    @profile = current_user.profile
  end
  
  def update
    @profile = current_user.profile

    if @profile.update_attributes(params[:profile])
      flash[:notice] = "Profile updated successfully."
      redirect_to user_root_path
    else
      flash[:alert] = @profile.errors.full_messages.join("<br />").html_safe
      render :edit
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  load_and_authorize_resource
  skip_authorize_resource :only => [:show]
    
  def new
  end
  
  def create
    @project.user_id = current_user.id
    if @project.save
      redirect_to root_path
    else
      redirect_to new_project_path
    end
  end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  load_and_authorize_resource
  skip_authorize_resource :only => [:show]

  def new
  end

  def create
    @publication.user_id = current_user.id

    if @publication.save
      flash[:notice] = "Publication successfully created."
      redirect_to dashboard_path
    else
      flash[:alert] = @publication.errors.full_messages.join("<br />").html_safe
      render :new
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource

    if resource.save
      set_flash_message :notice, :signed_up
      store_location!
      sign_in_and_redirect(resource_name, resource)
    else
      clean_up_passwords(resource)
      store_location!
      flash[:alert] = resource.errors.full_messages.join(", ")
      redirect_to root_url
    end
  end

  protected
    def store_location!
      session[:"#{scope}_return_to"] = attempted_path if request.get? && !http_auth?
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :redirect_logged_in_users
  
  def index
  end
  
  protected
  
  def redirect_logged_in_users
    redirect_to dashboard_path if current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/_education.html.haml
%li
	= education.institution_name

app/views/dashboard/_employment.html.haml
%li
	= employment.company_name

app/views/dashboard/_project.html.haml
%li
	= project.title

app/views/dashboard/_publication.html.haml
%li
	= publication.title

app/views/dashboard/index.html.haml
%div#header
	%h1 My Dashboard

	%div#errors
		- if notice
			%div#notice
				= notice
		- if alert
			%div#alert
				= alert

%div#dashboard_container
	%div.spacer
		%br/

	%div#resume_preview
		%div
			%h3
				= "#{current_user.display_name}'s Resume"

			%h4 Employment History
			- if @employments
				%ul
					= render :partial => "employment", :collection => @employments
			- else
				%ul
					%li No employment records. Add one!

			%h4 Education History
			- if @educations
				%ul
					= render :partial => "education", :collection => @educations
			- else
				%ul
					%li No education records. Add one!

			%h4 Publications
			- if @publications
				%ul
					= render :partial => "publication", :collection => @publications
			- else
				%ul
					%li No publications. Add one!

			%h4 Projects
			- if @projects
				%ul
					= render :partial => "project", :collection => @projects
			- else
				%ul
					%li No projects. Add one!

	%div.spacer
		%br/

	%div#sidebar
		%dl
			%dt
				My Resume
			%dd
				= link_to "Edit personal information", edit_profile_path
			%dd
				= link_to "Add employment history", new_employment_path
			%dd
				= link_to "Add education history", new_education_path
			%dd
				= link_to "Add publication history", new_publication_path
		%dl
			%dt
				My Portfolio
			%dd
				= link_to "Add project", new_project_path
		%dl
			%dt
				My Account
			%dd
				= link_to "Account settings", "#"
			%dd
				= link_to "Sign out", destroy_user_session_path

%div#footer

app/views/educations/new.html.haml
%div#header
	%h1 My Resume
	
	%div#errors
		- if notice
			%div#notice
				= notice
		- if alert
			%div#alert
				= alert

%div#content
	%h3 New education record
	= form_for(@education) do |f|
		%div
			= f.label :major, :class => :block
			= f.text_field :major, :class => "title block", :title => "your major here"
		%div
			= f.label :institution_name, :class => :block
			= f.text_field :institution_name, :class => "title block", :title => "name of the college/university"
		%div
			= f.label :location, :class => :block
			= f.text_field :location, :class => "title block", :title => "where they are located"
		%div
			= f.label :summary, :class => :block
			= f.text_area :summary, :class => "title block", :title => "short summary of your time here"
		= render :partial => "shared/date_fields", :locals => { :f => f, :hint => "Still studying here?" }
		%div
			= f.submit "Save", :class => "save_button"

%div.spacer
	%br/

%div#sidebar
	%h3 
	
%div#footer

app/views/employments/new.html.haml
%div#header
	%h1 My Resume

	%div#errors
		- if notice
			%div#notice
				= notice
		- if alert
			%div#alert
				= alert

%div#content
	%h3 New employment record
	= form_for(@employment) do |f|
		%div
			= f.label :job_title, :class => :block
			= f.text_field :job_title, :class => "title block", :title => "your job title here"
		%div
			= f.label :company_name, :class => :block
			= f.text_field :company_name, :class => "title block", :title => "name of the company"
		%div
			= f.label :location, :class => :block
			= f.text_field :location, :class => "title block", :title => "where they are located"
		%div
			= f.label :summary, :class => :block
			= f.text_area :summary, :class => "title block", :title => "short summary of your time here"
		= render :partial => "shared/date_fields", :locals => { :f => f, :hint => "Still at this job?" }
		%div
			= f.submit "Save", :class => "save_button"

%div.spacer
	%br/

%div#sidebar
	%h3 
	
%div#footer

app/views/portfolio_items/new.html.haml
%div#header
	%h1 My Portfolio

%div#content
	%h3 New portfolio item
	= form_for(@portfolio_item) do |f|
		%div
			= f.label :title, :class => :hidden
			= f.text_field :title, :class => "title", :title => "Title"
		%div
			= f.label :institution_name, :class => :hidden
			= f.text_field :institution_name, :class => "title", :title => "Institution name"
		%div
			= f.label :location, :class => :hidden
			= f.text_field :location, :class => "title", :title => "Location"
		%div
			= f.label :description, :class => :hidden
			= f.text_area :description, :class => "title", :title => "Summary"
		%div
			= f.label :hyperlink, :class => :hidden
			= f.text_area :hyperlink, :class => "title", :title => "Hyperlink"
		%div#start
			%p Start:
			= f.label :start_month, :class => :hidden
			= f.select :start_month, Date::MONTHNAMES.compact.zip((1..12).entries), { :include_blank => 'Month' }, { :class => "month" }
			= f.label :start_year, :class => :hidden
			= f.select :start_year, (1900..Time.now.year).to_a.reverse, :include_blank => 'Year'
		%div#current
			= f.label :current, "Still working on this project?", :class => "checkbox"
			= f.check_box :current, :class => "checkbox"
		%div#end{ :style => "display: none;" }
			%p End:
			= f.label :end_month, :class => :hidden
			= f.select :end_month, Date::MONTHNAMES.compact.zip((1..12).entries), { :include_blank => 'Month' }, { :class => "month" }
			= f.label :end_year, :class => :hidden
			= f.select :end_year, (1900..Time.now.year).to_a.reverse, :include_blank => 'Year'
		%div
			= f.file_field :image
		%div
			= f.submit "Save", :class => "save_button"

%div.spacer
	%br/

%div#sidebar
	%h3 
	
%div#footer

app/views/profiles/edit.html.haml
%div#header
	%h1 My Profile
	
	%div#errors
		- if notice
			%div#notice
				= notice
		- if alert
			%div#alert
				= alert

%div#content
	%h3 
	= form_for(@profile) do |f|
		%div
			= f.label :first_name
			= f.text_field :first_name, :class => "title", :title => "First name"
		%div
			= f.label :middle_name
			= f.text_field :middle_name, :class => "title", :title => "Middle name"
		%div
			= f.label :last_name
			= f.text_field :last_name, :class => "title", :title => "Last name"
		%div
			= f.label :summary
			= f.text_area :summary, :class => "title", :title => "Summary"
		%div
			= f.label :address_line_1
			= f.text_field :address_line_1, :class => "title", :title => "Address line 1"
		%div
			= f.label :address_line_2, :class => :hidden
			= f.text_field :address_line_2, :class => "title", :title => "Address line 2"
		%div
			= f.label :city
			= f.text_field :city, :class => "title", :title => "City"
		%div
			= f.label :state
			= f.text_field :state, :class => "title", :title => "State"
		%div
			= f.label :zip_code
			= f.text_field :zip_code, :class => "title", :title => "Zip code"
		%div
			= f.label :phone
			= f.text_field :phone, :class => "title", :title => "Phone number"
		%div
			= f.label :email
			= f.text_field :email, :class => "title", :title => "E-mail"
		%div
			= f.label :website
			= f.text_field :website, :class => "title", :title => "Website"
		%div
			= f.submit "Save", :class => "save_button"

%div.spacer
	%br/

%div#sidebar
	%h3 
	
%div#footer

app/views/projects/new.html.haml
%div#header
	%h1 My Portfolio

	%div#errors
		- if notice
			%div#notice
				= notice
		- if alert
			%div#alert
				= alert

%div#content
	%h3 New project
	= form_for(@project) do |f|
		%div
			= f.label :title, :class => :block
			= f.text_field :title, :class => "title block", :title => "title of the project"
		%div
			= f.label :institution_name, :class => :block
			= f.text_field :institution_name, :class => "title block", :title => "where you were working/studying"
		%div
			= f.label :location, :class => :block
			= f.text_field :location, :class => "title block", :title => "location of the institution"
		%div
			= f.label :description, :class => :block
			= f.text_area :description, :class => "title block", :title => "short summary of the project"
		%div
			= f.label :hyperlink, :class => :block
			= f.text_field :hyperlink, :class => "title block", :title => "link to more information"
		%div
			= f.label :image
			= f.file_field :image
		= render :partial => "shared/date_fields", :locals => { :f => f, :hint => "Still working on this project?" }
		%div
			= f.submit "Save", :class => "save_button"

%div.spacer
	%br/

%div#sidebar
	%h3 
	
%div#footer

app/views/publications/new.html.haml
%div#header
	%h1 My Resume

	%div#errors
		- if notice
			%div#notice
				= notice
		- if alert
			%div#alert
				= alert

%div#content
	%h3 New publication
	= form_for(@publication) do |f|
		%div
			= f.label :title, :class => :block
			= f.text_field :title, :class => "title block", :title => "title of the publication"
		%div
			= f.label :author, :class => :block
			= f.text_field :author, :class => "title block", :title => "author or authors"
		%div
			= f.label :publisher, :class => :block
			= f.text_field :publisher, :class => "title block", :title => "publisher/publication appeared in"
		%div
			= f.label :publication_date, :class => :block
			= f.text_field :publication_date, :class => "title block", :title => "date of publication or issue no."
		%div
			= f.label :description, :class => :block
			= f.text_area :description, :class => "title block", :title => "short summary of the publication"
		%div
			= f.label :hyperlink, :class => :block
			= f.text_field :hyperlink, :class => "title block", :title => "link to more information"
		%div
			= f.submit "Save", :class => "save_button"

%div.spacer
	%br/

%div#sidebar
	%h3

%div#footer

app/views/welcome/index.html.haml
%div#header
	%h1 ActiveResume
	%h3
		Create and share a beautiful online portfolio and resume.
	%div#errors
		- if notice
			%div#notice
				= notice
		- if alert
			%div#alert
				= alert

%div#sign_in_sign_up_container
	%div#sign_in_container
		%h2.form_title Sign in
		= form_for(:user, :url => session_path(:user)) do |f|
			%div
				= f.text_field :email, :class => "title", :title => "Email", :id => "user_sign_in_email"
			%div
				= f.password_field :password, :class => "title", :title => "Password", :id => "user_sign_in_password"
			%div
				= f.submit "Sign in", :class => "submit_button", :id => "user_sign_in_submit"

	%div.spacer
		%br/

	%div#sign_up_container
		%h2.form_title Sign up
		= form_for(:user, :url => registration_path(:user)) do |f|
			%div
				= f.text_field :email, :class => "title", :title => "Email", :id => "user_registration_email"
			%div
				= f.password_field :password, :class => "title", :title => "Password", :id => "user_registration_password"
			%div
				= f.password_field :password_confirmation, :class => "title", :title => "Password again", :id => "user_registration_password_confirmation"
			%div
				= f.submit "Sign up", :class => "submit_button", :id => "user_registration_submit"

%div#footer
	%p
		Copyright (c) 2010 Lee Edwards